# syntax=docker/dockerfile:1
FROM rust:alpine AS builder
RUN apk add --no-cache musl-dev
WORKDIR /src
COPY Cargo.toml Cargo.lock build.rs ./
COPY src/ src/
COPY benches/ benches/
RUN cargo build --features cli --release

FROM alpine:latest
COPY --from=builder /src/target/release/thaum /usr/local/bin/thaum
ENTRYPOINT ["thaum", "exec"]
