//! Unified test harness with runtime preconditions and unavailability reporting.
//!
//! Provides `#[testutil::test]` for annotating test functions. Tests can declare
//! runtime preconditions (e.g. "valgrind must be installed"), fixture injection,
//! custom display names, and labels for filtering. Tests whose preconditions are
//! not met show as `ignored` with an unavailability summary after all tests run.
//!
//! For dynamic test generation (e.g. from data files), use [`TestRunner::add`]
//! to register tests at runtime alongside attribute-registered ones.
//!
//! See the [README](../README.md) for usage instructions.

pub mod docker;

use std::path::Path;
use std::process::{Command, Stdio};
use std::sync::OnceLock;

use libtest_mimic::{Arguments, Trial};

// Re-export proc macros for consumers.
pub use testutil_macros::fixture;
#[deprecated(note = "use #[testutil::test(requires = [...])] instead")]
pub use testutil_macros::requires;
pub use testutil_macros::test;

// Re-export inventory so that macro-generated `inventory::submit!` calls resolve.
pub use inventory;

/// A precondition check function. Returns `Ok(())` if the requirement is met,
/// or `Err(reason)` if not.
pub type RequireFn = fn() -> Result<(), String>;

// Fixture system ==============================================================

/// Fixture lifetime scope.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Scope {
    /// Created once, shared across all tests. Teardown after all tests complete.
    Static,
    /// Fresh instance per test invocation. Teardown after each test.
    ///
    // TODO: Not yet implemented — currently behaves like `Static` because
    // `#[fixture]` always uses `OnceLock::get_or_init`. When needed, the
    // generated body should call `setup()` directly and `teardown()` after
    // the test function returns.
    PerTest,
}

/// A test resource that is set up before tests and torn down after.
///
/// Implement this trait on a struct, then annotate the impl block with
/// `#[testutil::fixture(...)]` to generate the storage and requirement
/// propagation.
pub trait Fixture: Send + Sync + Sized + 'static {
    const SCOPE: Scope;
    fn setup() -> Result<Self, String>;
    fn teardown(&self) {}
}

/// Generated by `#[testutil::fixture(...)]` — provides storage and requirement
/// metadata for a fixture type.
pub trait FixtureStorage: Fixture {
    /// Requirements inherited by any test using this fixture.
    const REQUIRES: &'static [RequireFn];
    /// The `OnceLock` holding the fixture instance (for `Static` scope).
    fn storage() -> &'static OnceLock<Result<Self, String>>;
}

/// Registered by the `#[testutil::fixture(...)]` macro for static fixtures.
/// Used by `run_tests()` to call teardown after all tests complete.
pub struct FixtureTeardownDef {
    pub teardown_if_initialized: fn(),
}

inventory::collect!(FixtureTeardownDef);

// Ignore ======================================================================

/// Whether a test is statically ignored.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Ignore {
    No,
    Yes,
    WithReason(&'static str),
}

// Test definition =============================================================

/// A test registered by `#[testutil::test(...)]` via inventory.
pub struct TestDef {
    pub name: &'static str,
    /// Display name (includes labels, custom name). `None` → use `name`.
    pub display_name: Option<&'static str>,
    pub requires: &'static [RequireFn],
    /// Requirements inherited from `#[fixture]` parameters. Each entry is a
    /// fixture type's `FixtureStorage::REQUIRES` slice.
    pub fixture_requires: &'static [&'static [RequireFn]],
    pub ignore: Ignore,
    pub body: fn(),
}

inventory::collect!(TestDef);

// Test runner =================================================================

/// A dynamically-added test (registered at runtime, not via proc macro).
struct DynTest {
    name: String,
    ignored: bool,
    body: Box<dyn FnOnce() + Send + 'static>,
}

/// Collects tests from both `#[testutil::test]` (inventory) and runtime
/// [`add`](TestRunner::add) calls, then runs them via libtest-mimic.
#[derive(Default)]
pub struct TestRunner {
    dynamic: Vec<DynTest>,
}

impl TestRunner {
    pub fn new() -> Self {
        Self::default()
    }

    /// Add a test that was generated at runtime (e.g. from a data file).
    ///
    /// The `body` closure should panic on failure (like a normal `#[test]`).
    pub fn add(&mut self, name: impl Into<String>, ignored: bool, body: impl FnOnce() + Send + 'static) {
        self.dynamic.push(DynTest {
            name: name.into(),
            ignored,
            body: Box::new(body),
        });
    }

    /// Run all tests (inventory-registered + dynamic) and exit.
    pub fn run(self) -> ! {
        self.run_tests().exit();
    }

    /// Run all tests and return the conclusion for post-run assertions.
    pub fn run_tests(self) -> libtest_mimic::Conclusion {
        let args = Arguments::from_args();
        let mut trials = Vec::new();
        let mut unavailable: Vec<(String, String)> = Vec::new();

        // Inventory-registered tests (from #[testutil::test]).
        for def in inventory::iter::<TestDef> {
            let trial_name = def.display_name.unwrap_or(def.name);

            // Static ignore — don't check preconditions, don't report as unavailable.
            if !matches!(def.ignore, Ignore::No) {
                trials.push(Trial::test(trial_name, || Ok(())).with_ignored_flag(true));
                continue;
            }

            let reasons: Vec<String> = def
                .requires
                .iter()
                .chain(def.fixture_requires.iter().flat_map(|s| s.iter()))
                .filter_map(|check| check().err())
                .collect();

            if reasons.is_empty() {
                let body = def.body;
                trials.push(Trial::test(trial_name, move || {
                    body();
                    Ok(())
                }));
            } else {
                let reason = reasons.join("; ");
                unavailable.push((trial_name.to_string(), reason));
                trials.push(Trial::test(trial_name, || Ok(())).with_ignored_flag(true));
            }
        }

        // Dynamic tests (from TestRunner::add).
        for dyn_test in self.dynamic {
            let body = dyn_test.body;
            let trial = Trial::test(dyn_test.name, move || {
                body();
                Ok(())
            })
            .with_ignored_flag(dyn_test.ignored);
            trials.push(trial);
        }

        let conclusion = libtest_mimic::run(&args, trials);

        if !unavailable.is_empty() {
            eprintln!("\n--- Unavailable ({}) ---", unavailable.len());
            for (name, reason) in &unavailable {
                eprintln!("  {name}: {reason}");
            }
        }

        // Teardown static fixtures.
        for def in inventory::iter::<FixtureTeardownDef> {
            (def.teardown_if_initialized)();
        }

        conclusion
    }
}

/// Shorthand: run only inventory-registered tests and exit.
pub fn run_all() -> ! {
    TestRunner::new().run();
}

// Precondition helpers ========================================================

/// Precondition: check that an executable is on PATH.
///
/// Returns `Ok(())` if `<name> --version` succeeds, or `Err` with a message.
pub fn probe_executable(name: &str) -> Result<(), String> {
    let ok = Command::new(name)
        .arg("--version")
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .is_ok_and(|s| s.success());
    if ok {
        Ok(())
    } else {
        Err(format!("{name} not installed"))
    }
}

/// Precondition: check that a file exists at the given path.
///
/// Returns `Ok(())` if the path exists, or `Err` with a message.
pub fn probe_path(path: impl AsRef<Path>) -> Result<(), String> {
    let path = path.as_ref();
    if path.exists() {
        Ok(())
    } else {
        Err(format!("{} not found", path.display()))
    }
}
