//! Unified test harness with runtime preconditions and unavailability reporting.
//!
//! Provides `#[testutil::test]` for annotating test functions. Tests can declare
//! runtime preconditions (e.g. "valgrind must be installed"), fixture injection,
//! custom display names, and labels for filtering. Tests whose preconditions are
//! not met show as `ignored` with an unavailability summary after all tests run.
//!
//! For dynamic test generation (e.g. from data files), use [`TestRunner::add`]
//! to register tests at runtime alongside attribute-registered ones.
//!
//! See the [README](../README.md) for usage instructions.

pub mod docker;

use std::path::Path;
use std::process::{Command, Stdio};
use std::sync::OnceLock;

use clap::Parser;
use libtest_mimic::{Arguments, Trial};

// Re-export proc macros for consumers.
pub use testutil_macros::fixture;
#[deprecated(note = "use #[testutil::test(requires = [...])] instead")]
pub use testutil_macros::requires;
pub use testutil_macros::test;

// Re-export inventory so that macro-generated `inventory::submit!` calls resolve.
pub use inventory;

/// A precondition check function. Returns `Ok(())` if the requirement is met,
/// or `Err(reason)` if not.
pub type RequireFn = fn() -> Result<(), String>;

// Fixture system ==============================================================

/// Fixture lifetime scope.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Scope {
    /// Created once, shared across all tests. Teardown after all tests complete.
    Static,
    /// Fresh instance per test invocation. Teardown after each test.
    ///
    // TODO: Not yet implemented — currently behaves like `Static` because
    // `#[fixture]` always uses `OnceLock::get_or_init`. When needed, the
    // generated body should call `setup()` directly and `teardown()` after
    // the test function returns.
    PerTest,
}

/// A test resource that is set up before tests and torn down after.
///
/// Implement this trait on a struct, then annotate the impl block with
/// `#[testutil::fixture(...)]` to generate the storage and requirement
/// propagation.
pub trait Fixture: Send + Sync + Sized + 'static {
    const SCOPE: Scope;
    fn setup() -> Result<Self, String>;
    fn teardown(&self) {}
}

/// Generated by `#[testutil::fixture(...)]` — provides storage and requirement
/// metadata for a fixture type.
pub trait FixtureStorage: Fixture {
    /// Requirements inherited by any test using this fixture.
    const REQUIRES: &'static [RequireFn];
    /// The `OnceLock` holding the fixture instance (for `Static` scope).
    fn storage() -> &'static OnceLock<Result<Self, String>>;
}

/// Registered by the `#[testutil::fixture(...)]` macro for static fixtures.
/// Used by `run_tests()` to call teardown after all tests complete.
pub struct FixtureTeardownDef {
    pub teardown_if_initialized: fn(),
}

inventory::collect!(FixtureTeardownDef);

// Ignore ======================================================================

/// Whether a test is statically ignored.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Ignore {
    No,
    Yes,
    WithReason(&'static str),
}

// Test definition =============================================================

/// A test registered by `#[testutil::test(...)]` via inventory.
pub struct TestDef {
    pub name: &'static str,
    /// Display name (custom name). `None` → use `name`.
    pub display_name: Option<&'static str>,
    pub requires: &'static [RequireFn],
    /// Requirements inherited from `#[fixture]` parameters. Each entry is a
    /// fixture type's `FixtureStorage::REQUIRES` slice.
    pub fixture_requires: &'static [&'static [RequireFn]],
    pub ignore: Ignore,
    /// Labels for filtering. Stored in libtest-mimic's `kind` field joined by `:`.
    pub labels: &'static [&'static str],
    pub body: fn(),
}

inventory::collect!(TestDef);

// Label filtering =============================================================

enum LabelSelector {
    Include(String),
    Exclude(String),
}

/// Extract label selectors from `--label` CLI args and the `TESTUTIL_LABEL`
/// env var. Returns the selectors and the remaining CLI args (for libtest-mimic).
///
/// Sources (combined):
/// - `--label docker` / `--label=docker,!slow` on the command line
/// - `TESTUTIL_LABEL=docker,!slow` environment variable
///
/// The env var is the portable mechanism (works with `cargo test`, `cargo nextest`,
/// or direct binary invocation). `--label` only works when running a specific
/// test binary directly.
fn extract_label_filters() -> (Vec<LabelSelector>, Vec<String>) {
    let args: Vec<String> = std::env::args().collect();
    let mut selectors = Vec::new();
    let mut remaining = Vec::new();
    let mut i = 0;
    while i < args.len() {
        if args[i] == "--label" {
            i += 1;
            if i < args.len() {
                parse_label_arg(&args[i], &mut selectors);
            }
        } else if let Some(val) = args[i].strip_prefix("--label=") {
            parse_label_arg(val, &mut selectors);
        } else {
            remaining.push(args[i].clone());
        }
        i += 1;
    }

    // Also read from TESTUTIL_LABEL env var.
    if let Ok(val) = std::env::var("TESTUTIL_LABEL") {
        parse_label_arg(&val, &mut selectors);
    }

    (selectors, remaining)
}

fn parse_label_arg(val: &str, selectors: &mut Vec<LabelSelector>) {
    for part in val.split(',') {
        let part = part.trim();
        if part.is_empty() {
            continue;
        }
        if let Some(label) = part.strip_prefix('!') {
            selectors.push(LabelSelector::Exclude(label.to_string()));
        } else {
            selectors.push(LabelSelector::Include(part.to_string()));
        }
    }
}

/// Check whether a test with the given labels passes the label filter.
///
/// - Includes form a union: test must match ANY include.
/// - Excludes subtract: test must not match ANY exclude.
/// - No includes → all tests included by default.
/// - No selectors → all tests pass.
fn label_matches(test_labels: &[&str], selectors: &[LabelSelector]) -> bool {
    let has_includes = selectors.iter().any(|s| matches!(s, LabelSelector::Include(_)));

    let included = if has_includes {
        selectors.iter().any(|s| match s {
            LabelSelector::Include(l) => test_labels.contains(&l.as_str()),
            LabelSelector::Exclude(_) => false,
        })
    } else {
        true
    };

    let excluded = selectors.iter().any(|s| match s {
        LabelSelector::Exclude(l) => test_labels.contains(&l.as_str()),
        LabelSelector::Include(_) => false,
    });

    included && !excluded
}

// Test runner =================================================================

/// A dynamically-added test (registered at runtime, not via proc macro).
struct DynTest {
    name: String,
    ignored: bool,
    labels: Vec<String>,
    body: Box<dyn FnOnce() + Send + 'static>,
}

/// Collects tests from both `#[testutil::test]` (inventory) and runtime
/// [`add`](TestRunner::add) calls, then runs them via libtest-mimic.
#[derive(Default)]
pub struct TestRunner {
    dynamic: Vec<DynTest>,
}

impl TestRunner {
    pub fn new() -> Self {
        Self::default()
    }

    /// Add a test that was generated at runtime (e.g. from a data file).
    ///
    /// The `body` closure should panic on failure (like a normal test).
    pub fn add(
        &mut self,
        name: impl Into<String>,
        labels: &[&str],
        ignored: bool,
        body: impl FnOnce() + Send + 'static,
    ) {
        self.dynamic.push(DynTest {
            name: name.into(),
            ignored,
            labels: labels.iter().map(|s| s.to_string()).collect(),
            body: Box::new(body),
        });
    }

    /// Run all tests (inventory-registered + dynamic) and exit.
    pub fn run(self) -> ! {
        self.run_tests().exit();
    }

    /// Run all tests and return the conclusion for post-run assertions.
    pub fn run_tests(self) -> libtest_mimic::Conclusion {
        let (label_selectors, remaining_args) = extract_label_filters();
        let args = Arguments::parse_from(remaining_args);
        let mut trials = Vec::new();
        let mut unavailable: Vec<(String, String)> = Vec::new();

        // Inventory-registered tests (from #[testutil::test]).
        for def in inventory::iter::<TestDef> {
            // Label filtering — skip entirely (not ignored, just absent).
            if !label_selectors.is_empty() && !label_matches(def.labels, &label_selectors) {
                continue;
            }

            let trial_name = def.display_name.unwrap_or(def.name);
            let kind = def.labels.join(":");

            // Static ignore — don't check preconditions, don't report as unavailable.
            if !matches!(def.ignore, Ignore::No) {
                let trial = Trial::test(trial_name, || Ok(())).with_ignored_flag(true);
                let trial = if kind.is_empty() { trial } else { trial.with_kind(kind) };
                trials.push(trial);
                continue;
            }

            let reasons: Vec<String> = def
                .requires
                .iter()
                .chain(def.fixture_requires.iter().flat_map(|s| s.iter()))
                .filter_map(|check| check().err())
                .collect();

            if reasons.is_empty() {
                let body = def.body;
                let trial = Trial::test(trial_name, move || {
                    body();
                    Ok(())
                });
                let trial = if kind.is_empty() { trial } else { trial.with_kind(kind) };
                trials.push(trial);
            } else {
                let reason = reasons.join("; ");
                unavailable.push((trial_name.to_string(), reason));
                let trial = Trial::test(trial_name, || Ok(())).with_ignored_flag(true);
                let trial = if kind.is_empty() { trial } else { trial.with_kind(kind) };
                trials.push(trial);
            }
        }

        // Dynamic tests (from TestRunner::add).
        for dyn_test in self.dynamic {
            let dyn_labels: Vec<&str> = dyn_test.labels.iter().map(|s| s.as_str()).collect();
            if !label_selectors.is_empty() && !label_matches(&dyn_labels, &label_selectors) {
                continue;
            }

            let kind = dyn_test.labels.join(":");
            let body = dyn_test.body;
            let trial = Trial::test(dyn_test.name, move || {
                body();
                Ok(())
            })
            .with_ignored_flag(dyn_test.ignored);
            let trial = if kind.is_empty() { trial } else { trial.with_kind(kind) };
            trials.push(trial);
        }

        let conclusion = libtest_mimic::run(&args, trials);

        if !unavailable.is_empty() {
            eprintln!("\n--- Unavailable ({}) ---", unavailable.len());
            for (name, reason) in &unavailable {
                eprintln!("  {name}: {reason}");
            }
        }

        // Teardown static fixtures.
        for def in inventory::iter::<FixtureTeardownDef> {
            (def.teardown_if_initialized)();
        }

        conclusion
    }
}

/// Shorthand: run only inventory-registered tests and exit.
pub fn run_all() -> ! {
    TestRunner::new().run();
}

// Precondition helpers ========================================================

/// Precondition: check that an executable is on PATH.
///
/// Returns `Ok(())` if `<name> --version` succeeds, or `Err` with a message.
pub fn probe_executable(name: &str) -> Result<(), String> {
    let ok = Command::new(name)
        .arg("--version")
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .is_ok_and(|s| s.success());
    if ok {
        Ok(())
    } else {
        Err(format!("{name} not installed"))
    }
}

/// Precondition: check that a file exists at the given path.
///
/// Returns `Ok(())` if the path exists, or `Err` with a message.
pub fn probe_path(path: impl AsRef<Path>) -> Result<(), String> {
    let path = path.as_ref();
    if path.exists() {
        Ok(())
    } else {
        Err(format!("{} not found", path.display()))
    }
}
